# Generated by Django 6.0.3 on 2026-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "tb_disciplinas",
            },
        ),
    ]
